/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package it133;

import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author i-Tech Software Academy @Nagercoil
 */
public class SmartContracts extends javax.swing.JFrame {
    static String data;
    static int i=0;
    protected DatagramSocket socket = null;
    /**
     * Creates new form SmartContracts
     */
    public SmartContracts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SMART CONTRACTS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(260, 30, 260, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 700, 260);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Process");
        jButton1.setActionCommand("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(640, 380, 110, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            
            byte[] buf = new byte[500000];
            socket = new DatagramSocket(4450);
//            data=jTextArea1.getText();
            System.out.print(data);
            buf = data.getBytes();
            InetAddress group = InetAddress.getByName("230.0.0.1");//230.0.0.5");
            DatagramPacket packet = new DatagramPacket(buf, buf.length,
                    group, 4460);
            socket.send(packet);
            socket.close();
JOptionPane.showMessageDialog(this, "Candidate Processed");
jButton1.setEnabled(false);
jTextArea1.setText("");


socket = new DatagramSocket(4490);
//            data=jTextArea1.getText();
            System.out.print(data);
            buf = data.getBytes();
InetAddress group1 = InetAddress.getByName("230.0.0.1");//230.0.0.5");
            DatagramPacket packet1 = new DatagramPacket(buf, buf.length,
                    group1, 4499);
            socket.send(packet1);
            socket.close();

        } catch (Exception e) {
            System.out.println("An error occurred." + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartContracts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartContracts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartContracts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartContracts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartContracts().setVisible(true);
            }
        });
        MulticastSocket socket = new MulticastSocket(4418);
        InetAddress address = InetAddress.getByName("230.0.0.1");
        socket.joinGroup(address);
        DatagramPacket packet;
        while (true) {
            //jTextArea1.setText("");
           
        InetAddress ipAddr = InetAddress.getLocalHost();
            //
            byte[] buf = new byte[500000];
            packet = new DatagramPacket(buf, buf.length);
            socket.receive(packet);
            int k=2000;
            String received = new String(packet.getData());
            received = received.trim();
            
            // ta.setText("");
            String ipaddr = "";
            try {

                //for (i = 1; i <= 1010; i = i + 10) {
                    //PB.setValue(i);

                    
               // }
               System.out.println(received);
               if(String.valueOf(received).equalsIgnoreCase("polled")){
                jButton1.setEnabled(true);
                data=null;
            }
                else
               {
                   String[] dataArray = received.split(",");
//                System.out.println(Arrays.toString(dataArray));
                ipaddr = ipAddr.getHostAddress().toString();
                jTextArea1.append("\nVoter ID : "+dataArray[1]);
                jTextArea1.append("\nCandidate Name : "+dataArray[0]);
                jTextArea1.append("\nCandidate Code : "+dataArray[2]);
                
                
                data=data+","+String.valueOf(received);
                System.out.println(data);
               }
               
                Thread.sleep(k);
                } catch (Exception e) {
                System.out.println(e);
            }
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
